export const BACKGROUND_PRESETS = [
  {
    id: "minecraft",
    name: "마인크래프트 스타일",
    prompt: `Transform only the surroundings of the uploaded photo into a realistic Minecraft block style, without altering the subject at all — keep the person's face, body, pose, clothing, colors, lighting, and composition exactly the same. Convert the entire background environment into Minecraft blocks: iconic cubic geometry, large pixel textures, distinct voxel edges, and simplified materials (grass blocks, stone, wood planks, etc.) placed logically to match the real scene structure. Any objects, buildings, ground, trees, sky, or props should become Minecraft-style versions while staying consistent with the original spatial layout and perspective. Maintain clean block lighting and soft ambient shadows. Ensure there are no changes at all to the subject — no pixelation, no style change, no alterations to face, body, or proportions. Aim for a seamless fusion of Minecraft world and realistic subject. Hard Rules: Do not change the subject's appearance in any way. Do not cover or distort the subject with pixels or blocks. Preserve composition, camera angle, scale, and depth exactly as in the uploaded image.`,
  },
  {
    id: "lego",
    name: "레고 스타일",
    prompt: `Use the uploaded reference image as the source. OVERALL STYLE & AESTHETIC: High quality cinematic LEGO photography with a macro lens feel. Mixed media realism: a fully photorealistic human subject integrated into a 100 percent brick built LEGO world. SUBJECT RULES (CRITICAL): The main human subject from the reference image must remain 100 percent photorealistic. Preserve original skin texture, pores, hair strands, facial features, and natural lighting on the person. Do NOT apply any plastic, toy, or LEGO texture to the human subject. OBJECT CONVERSION (CRITICAL): Every single object held by or touching the person must be replaced with its LEGO equivalent. This includes flowers, bouquets, bags, tools, accessories, or props. Flowers must be rebuilt using LEGO Botanical Collection style: Visible plastic petal pieces, Glossy ABS plastic material, Distinct LEGO stems and connectors. ENVIRONMENT RULES (MANDATORY): Analyze the original background and rebuild it entirely using LEGO bricks. Ground surfaces must use visible LEGO studs. Roads, walls, or flat surfaces must use LEGO smooth tiles. Trees, grass, and plants must be official LEGO foliage pieces with: Visible seams, Injection mold marks, Plastic geometry. MATERIALITY: All LEGO elements must have: Realistic plastic reflections, Subtle scratches and wear, High quality glossy ABS finish. COMPOSITION & CAMERA: Match the exact framing and camera angle of the reference image. Use shallow depth of field to emphasize the human subject while keeping LEGO details readable. LIGHTING: Cinematic studio lighting. Ensure light interacts differently with: Photorealistic human skin (soft, natural diffusion), LEGO plastic surfaces (specular highlights, glossy reflections). NEGATIVE PROMPT (STRICT): No real flowers, No organic petals, No real trees, No realistic fabric in the background, No blurred plastic, No toy-like skin, No plastic face.`,
  },
  {
    id: "clay",
    name: "클레이 스타일",
    prompt: `Use the uploaded image as the only source of identity for the main subject. Core Transformation: Transform everything except the main subject into a handcrafted clay stop-motion world, as if the environment were built for a Laika or Aardman-style stop-motion film. Buildings, streets, sidewalks, floors, walls, furniture, vehicles, trees, props, background objects, and scenery → All rendered as sculpted clay models. Sky, clouds, lighting ambience → Stylized clay sky with soft, imperfect textures. Subject Preservation (STRICT): The main subject must remain 100% realistic and unchanged. Preserve: Face, skin texture, hair, clothing, accessories, Body proportions, pose, expression, Photographic realism and sharpness. No stylization applied to the subject. Clay / Stop-Motion Style Rules: Clay textures must look: Hand-molded, Slightly uneven, Soft, tactile, and imperfect. Visible: Finger smudges, Tool marks, Subtle seams where clay pieces meet. Shapes: Rounded edges, Chunky forms, Slight asymmetry (not perfectly straight). Lighting & Rendering: Stop-motion studio lighting: Soft directional light, Gentle shadows, Slight falloff and depth. Matte clay surfaces. No gloss unless appropriate (e.g., wet clay look on roads). Visual Contrast (IMPORTANT): Strong contrast between: Realistic subject, Clay-crafted environment. The subject should clearly feel "placed inside" a clay world. Camera & Composition: Match the original camera angle and framing from the uploaded image. Maintain natural perspective and depth. Ensure the subject remains the visual focal point. Negative Prompt (STRICT): No stylization on the subject, No cartoon or clay texture on skin, hair, or clothes, No plastic, rubber, or 3D CGI look, No voxel, LEGO, pixel, anime, or illustration styles, No smooth or digitally perfect surfaces. Output Quality: High detail, Cinematic stop-motion realism, Believable scale and spatial consistency.`,
  },
  {
    id: "sims",
    name: "심즈 스타일",
    prompt: `Use the uploaded image as the base reference. Core Instruction: Transform all surroundings in the image into The Sims–style interior / world, exactly like the official The Sims games. Do NOT transform the main subject. The main subject must remain fully realistic and unchanged. What to Transform (STRICT): Architecture and buildings, Interior walls, floors, ceilings, Furniture and decor, Streets, sidewalks, roads, Cars and vehicles, Sky, clouds, lighting environment, Plants, trees, terrain, ground, Background objects and props. Everything except the main subject should appear as if it exists inside The Sims game world. What NOT to Transform (STRICT): Main subject's face, body, skin texture, Main subject's clothing, hair, accessories, Main subject's pose, expression, proportions. Main subject must remain photorealistic and clearly separated from the stylized environment. The Sims Visual Style (VERY IMPORTANT): Match the official The Sims aesthetic: Clean, slightly exaggerated geometry, Smooth surfaces with subtle plastic-like finish, Soft global illumination and even lighting, Bright but balanced color palette, Simplified textures (no hyper-real detail), Rounded edges on furniture and architecture, Game-engine look (The Sims 4 style), Interiors should feel like a build/buy mode room, Exteriors should feel like a live neighborhood lot. Lighting & Atmosphere: Soft ambient lighting like in The Sims gameplay, No harsh shadows, Bright, cozy, evenly lit environment, Sky rendered in stylized Sims-style gradient with fluffy clouds. Composition Rules: Keep the original camera angle and framing, Preserve depth and perspective, Ensure the subject visually "belongs" in the space while staying realistic, The environment should clearly contrast the real subject. Quality & Realism Balance: Subject: real photo realism, Environment: game-engine Sims realism, Clean edges where subject meets environment (no melting or blending). Negative Prompt (STRICT): No pixel art, No voxel, LEGO, Minecraft, or clay styles, No anime, cartoon, or hand-drawn illustration, No painterly textures, No realism applied to surroundings, No stylization applied to the subject, No Sim plumbob above the subject's head. Output Goal: A realistic person placed inside a fully transformed Sims interior or Sims world, indistinguishable from an actual The Sims gameplay screenshot — except for the real human subject.`,
  },
  {
    id: "pastel",
    name: "파스텔 일러스트 스타일",
    prompt: `Transform the entire scene into a mixed-media illustration with hand-drawn cartoon overlays. Convert the buildings, windows, street lamps, bus, plants, sky, and ground into outlined cartoon sketches with bright, colorful fills. Add doodles to fill the background, swirling arrows around the subject(s), cartoon clouds in the sky, hearts, stars, panels, and playful sketch lines across the scene. Add climbing vines and decorative doodles to the lamp post and buildings. Keep the subject(s) fully realistic and untouched.`,
  },
  {
    id: "apocalypse",
    name: "지구 종말 스타일",
    prompt: `Use the uploaded image as the only source of the main subject. Hard Rule: Do not change the subject's face, body, pose, expression, hairstyle, clothing, skin tone, or proportions in any way. The subject must remain pixel identical in identity and pose. No beautification, no stylization, no redraw, no facial alteration. Transformation Goal: Transform only the surrounding environment into a cinematic dystopian end of the world setting, while keeping the subject untouched and fully recognizable. Environment & World Design: Replace the background with a post apocalyptic landscape. Crumbling buildings, collapsed structures, broken roads, exposed rebar. Burned out vehicles, debris, shattered glass, scattered rubble. Smoke plumes rising in the distance. Ash and dust in the air. Dark storm clouds, heavy overcast sky, polluted atmosphere. Faint orange or red glow on the horizon from distant fires. Subtle embers floating in the air. Optional cracked ground or flooded streets depending on scene logic. Lighting & Atmosphere: Moody, low key cinematic lighting. High contrast with deep shadows. Cool desaturated tones with selective warm highlights from fire or explosions. Volumetric fog and haze for depth. Directional light consistent with the original photo's lighting. No light spill or color cast affecting the subject's skin or clothing. Composition Rules: Preserve original camera angle, framing, and perspective. Subject stays in the exact same position in the frame. Environmental destruction must feel physically integrated behind the subject. No objects overlapping or covering the subject. Texture & Realism: Hyper realistic textures for rubble, concrete, metal, smoke, and dust. Natural scale and depth. No surreal elements unless explicitly dystopian. No sci fi armor, no fantasy creatures, no zombies unless requested. Negative Prompt: Do not: Alter the subject's face, body, clothing, or pose, Add damage, dirt, blood, or effects to the subject, Stylize the subject, Change camera angle or zoom, Turn the subject into a character or illustration, Add text, logos, or UI elements. Output: Ultra realistic, cinematic, high detail dystopian environment with the original subject preserved perfectly in contrast against an end of the world backdrop.`,
  },
];
